USE [Judoca]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_FILIADO](
	[ID] [int] IDENTITY (1,1) NOT NULL,
	[NOME] [varchar](120) NULL,
	[ANIVERSARIO] [date] NULL,
	[DATA_CADASTRO] [date] NULL,
	[REGISTRO_CBJ] [varchar](120) NULL,
	[TELEFONE1] [char](9) NULL,
	[TELEFONE2] [char](9) NULL,
	[EMAIL] [varchar](60) NULL,
	[CPF] [varchar](12) NULL,
	[RG] [varchar](10) NULL,
	[ORGAO_EXP] [varchar](5) NULL,
	[OBSERVACAO] [varchar](255) NULL,
	[TIPO] [char](1) NULL

CONSTRAINT [PK_FILIADO_PASS] PRIMARY KEY NONCLUSTERED(
	[ID] ASC
	)

)	

GRANT SELECT,UPDATE,DELETE,INSERT ON [TBL_FILIADO] TO rapaziada